### ISSUE TITLE
Colab Notebook

### ISSUE THREAD

**Issue by dhruvrajsaharan** [jiali-zheng/Design2Cloth#2]
Hi team

can a colab notebook be provided, currently having issues with conda installation from environment.yaml

thanks

**Comment by wwwddd1** [comment]
Dear team,
I hope this message finds you well. I am writing to seek assistance with an ImportError I've encountered while trying to use your meshudf library in my project.

When I attempt to import get_mesh_from_udf and GridFiller from meshudf.meshudf, I receive the following error:

Traceback (most recent call last):
  File "inference.py", line 7, in <module>
    from meshudf.meshudf import get_mesh_from_udf, GridFiller
  File "/home/user/Design2Cloth-main/Design2Cloth-main/meshudf/meshudf.py", line 20, in <module>
    from meshudf._marching_cubes_lewiner import udf_mc_lewiner
  File "/home/user/Design2Cloth-main/Design2Cloth-main/meshudf/_marching_cubes_lewiner.py", line 6, in <module>
    from meshudf import _marching_cubes_lewiner_cy
ImportError: cannot import name '_marching_cubes_lewiner_cy' from 'meshudf' (unknown location)
Steps Taken:
I have ensured that all dependencies are installed correctly.
I have checked the file paths and Python environment to ensure everything is set up properly.
I have attempted to recompile any Cython extensions, but the issue persists.
Additional Information:
I am running the code in a virtual environment with all the necessary packages installed.
I have reviewed the documentation and GitHub Issues, but haven't found a solution to this specific problem.
I would greatly appreciate any guidance or suggestions you might have to resolve this issue. If there are any additional details or logs you need, please let me know.
Thank you for your time and assistance.
Best regards,

**Comment by jiali-zheng** [comment]
> marching_cubes_lewiner_cy

Hi @wwwddd1 ,

Thank you for your message.

Can you try to build and install meshudf by

cd meshudf
source setup.sh

and try again?

**Comment by jiali-zheng** [comment]
> colab notebook

Thank you for your interest! The Colab notebook is still being prepared but we are not sure about the release timeline. Meanwhile, our code/documentation may help, and I’m happy to answer any specific questions:)
